version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /cx-jupyterlite
    schedule:
      interval: weekly
    groups:
      npm-jupyterlite:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /crates/cx-wasm/www
    schedule:
      interval: weekly
    groups:
      npm-wasm-www:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python:
        patterns:
          - "*"
